// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1of-G4NKqIt2vBI977lSXWEqiQoYr0Y',
    appId: '1:470239105095:web:a0119631afa7f0b5432162',
    messagingSenderId: '470239105095',
    projectId: 'jiltone-store',
    authDomain: 'jiltone-store.firebaseapp.com',
    storageBucket: 'jiltone-store.firebasestorage.app',
    measurementId: 'G-1EDSE61V2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAByZCUXs4EetsAvYjosyDY4IXCaToZYto',
    appId: '1:470239105095:android:5d85b892b65025b1432162',
    messagingSenderId: '470239105095',
    projectId: 'jiltone-store',
    storageBucket: 'jiltone-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lc9dwmi0tkG-YIcp2f1AsOv93kwFgSc',
    appId: '1:470239105095:ios:396d75de150a6e1e432162',
    messagingSenderId: '470239105095',
    projectId: 'jiltone-store',
    storageBucket: 'jiltone-store.firebasestorage.app',
    iosClientId: '470239105095-4qa8v44u9tab2esclhmhuveafmkuaac1.apps.googleusercontent.com',
    iosBundleId: 'com.jiltone.jiltoneStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA1of-G4NKqIt2vBI977lSXWEqiQoYr0Y',
    appId: '1:470239105095:web:b492a220705e3343432162',
    messagingSenderId: '470239105095',
    projectId: 'jiltone-store',
    authDomain: 'jiltone-store.firebaseapp.com',
    storageBucket: 'jiltone-store.firebasestorage.app',
    measurementId: 'G-GC56H7FDD0',
  );
}
